### ISSUE TITLE
Project Meeting -- 09/18/2019 @ 13:00

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#15]
**Meeting Date:** September 18, 2019 
**Topic:** Weekly Meeting
**Attendees:** @bill-baumgartner 

**Proposed Agenda:**
- [ ] Comparing full KG to full KG + reasoner inferences  
  - Discuss KaBOB script used to convert anonymous nodes to non-anonymous nodes to properly add edges inferred from running reasoners   
- [ ] Continue discussing developing KR for clinical to biological concept mappings (see #12)

**Comment by callahantiff** [comment]
**UPDATE:**  
> **Proposed Agenda:**
> * [ ]  Comparing full KG to full KG + reasoner inferences
>   * Discuss KaBOB script used to convert anonymous nodes to non-anonymous nodes to properly add edges inferred from running reasoners

Before next week's meeting, I need to do the following:  
- [ ] Verify that all instances have a valid URI and that this information is correctly recorded in a node-level dictionary  
- [ ] Verify node and edge count pre- and post-reasoner to ensure that all newly inferred edges are actually being added to the original KG.  
- [ ] Verify that the assertions ignored by the reasoner are not removed from the KG and thus included in the final version when incorporating the newly inferred assertions.  
- [ ] Trying running the reasoner without removing disjointness axioms to confirm whether or not those need to be manually removed prior to reasoning.  
- [ ] If manually removing disjointness axioms, figure out why the numbers before and after removal are not matching up.  

> * [ ]  Continue discussing developing KR for clinical to biological concept mappings (see #12)

- [ ] Before next week's meeting gather more complex examples, those that may be difficult to create constructors from so a strategy can be discussed.

***

@bill-baumgartner - since these are still things I need to address and are likely to be discussed at our next meeting I will leave this issue open. Also, please feel free to edit/comment if there is anything I missed or worth clarifying. 😄

**Comment by callahantiff** [comment]
@bill-baumgartner - for our meeting tomorrow (_10/9/19_) I was hoping we could talk about the inaccurate assertions that resulted from running ELK on HPO. The Spreadsheet documenting these issues can be found [here](https://docs.google.com/spreadsheets/d/1-2i3HFQ9d3F9sp77wqvYQYENHGDL6mq5CmdzIvdO54M/edit#gid=0).

**Goal:**  
- [ ] Submit an issue to HPO describing our findings

**Comment by callahantiff** [comment]
**Post-Meeting Update**   
 
> @bill-baumgartner - for our meeting tomorrow (_10/9/19_) I was hoping we could talk about the inaccurate assertions that resulted from running ELK on HPO. The Spreadsheet documenting these issues can be found [here](https://docs.google.com/spreadsheets/d/1-2i3HFQ9d3F9sp77wqvYQYENHGDL6mq5CmdzIvdO54M/edit#gid=0).
> 
> **Goal:**
> * [ ]  Submit an issue to HPO describing our findings

**TODOs:**  
- [ ] GO back through reasoner results and reorganize to indicate when an error is from the definition or when it is the result of an error in a different ontology that is used in HPO's definition.    
- [ ] Delete all classes except for `red hair` and `skin rash` and then run the reasoner. Then, modify each classes' definition to remove `red` and run reasoner again.  

@bill-baumgartner - should I add anything else to this list?

**Comment by callahantiff** [comment]
Closing this for now and will open new issues for relevant parts of this as they come up through our reasoner evaluation and the v3.0.0 build.
