### ISSUE TITLE
Create Docker Container for Neo4J instance

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#47]
Create a new `Dockerfile` that contains a Neo4J instance for each OWL-NETS version of the parameterized KGs.

**Comment by callahantiff** [comment]
@bill-baumgartner - per our discussion via Slack can I confirm you are still willing to help with this?

**Comment by callahantiff** [comment]
@bill-baumgartner - are you still willing to help me with this? I liked the idea you slacked me about a few weeks ago, if that's still on the table? 😄

**Comment by callahantiff** [comment]
### TASK  
**Task Type:** [`INFRASTRUCTURE`](https://github.com/callahantiff/PheKnowLator/projects/8#card-51635998)   
Configure Neo4J to work with Docker container and CI/CD framework


#### TODO  
- [ ] Decide on what [Neo4J](https://neo4j.com/) services to use  
  - Bloom?
  - Aura?  
- [ ] Configure with Docker Container  
- [ ] Integrate with GitHub Actions CI/CD (#68)

**Comment by bill-baumgartner** [comment]
Looks like [Aura has Bloom built-in](https://neo4j.com/press-releases/neo4j-aura-for-google-cloud-platform-ga/) so that seems like the way to go for hosting a public Neo4j instance. Do you think hosting one version in Neo4j is adequate? Or do we need to host multiple versions? As far as I can tell, we don't we need a Docker image to host in Aura, so maybe we should split the hosting work out into a new Issue.

We can still create Docker images for each OWL-NETS version of the parameterized KGs. These would be targeted to users so they can select the version that best suits their needs. 

Some resources that might come in handy as we work on the Docker images:
* [official Neo4j Docker image docs](https://neo4j.com/developer/docker-run-neo4j/)
* [example of integrating Bloom w/Neo4j Docker](https://gist.github.com/sarmbruster/883e405cf8db04c9a3179d5dc9f300b3)

**Comment by callahantiff** [comment]
Closing this for now since it's no longer a pending todo item. Feel free to re-open if we decide to go this route again.
