### ISSUE TITLE
Verify KG Output File Types

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#55]
### TASK  
**Task Type:** [`CODEBASE`](https://github.com/callahantiff/PheKnowLator/projects/8#card-51636107)

Improve the naming of generated data and verify output file types we will provided for each build.

#### TODO  

**Problem:**   
- [x] Add `n-triples` format for OWL-NETS builds  
- [x] Check input file specifications for GraphDB  
- [x] Check input file specifications for Neo4J  
- [ ] Fix OWL-NETS build output  
  - *Problem:* When running the OWL-NETS parameter, the full `.owl` file created during the build is named "NoOWL" when when it is actually the original OWL KG. Make sure to fix the name of this file to ensure it's clear that this is not part of the OWL-NETS output. Thanks to @rkboyce for helping identify this error!

**Comment by callahantiff** [comment]
Done as part of #84
