### ISSUE TITLE
Add integer and identifiers to node metadata

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#58]
**Problem:** Right now the node metadata that is output is keyed by an identifier, which means if you use the integer edge lists, but want node labels you have to use the provided dictionary that maps node integers to identifiers first. 

**Solution:** In the next iteration, I will add a new column that includes the identifier and the integer. Examples of each output are shown below.

**An example of the current output:**
node_id | label | description/definition | synonym
:--: | :--: | -- | --
388324 | INCA1 | INCA1 has locus group 'protein-coding' and is located on chromosome 17 (map_location: 17p13.2). | HSD45protein INCA1
92106 | OXNAD1 | OXNAD1 has locus group 'protein-coding' and is located on chromosome 3 (map_location: 3p25.1-p24.3). | oxidoreductase NAD-binding domain-containing protein 1
56140 | PCDHA8 | PCDHA8 has locus group 'protein-coding' and is located on chromosome 5 (map_location: 5q31.3). | PCDH-ALPHA8protocadherin alpha-8|KIAA0345-like 6|PCDH-alpha-8

<br>

**An example of the improved output:**
node_integer | node_id | label | description/definition | synonym
:--: | :--: | :--: | -- | --
0 | 388324 | INCA1 | INCA1 has locus group 'protein-coding' and is located on chromosome 17 (map_location: 17p13.2). | HSD45protein INCA1
1 | 92106 | OXNAD1 | OXNAD1 has locus group 'protein-coding' and is located on chromosome 3 (map_location: 3p25.1-p24.3). | oxidoreductase NAD-binding domain-containing protein 1
2 | 56140 | PCDHA8 | PCDHA8 has locus group 'protein-coding' and is located on chromosome 5 (map_location: 5q31.3). | PCDH-ALPHA8protocadherin alpha-8|KIAA0345-like 6|PCDH-alpha-8

**Comment by callahantiff** [comment]
- [ ] Add relation information to metadata file. Will require a simple helper method to parse the graph and obtain relation labels

**Comment by callahantiff** [comment]
Verify node identifiers in output metadata, formatting for ensemble transcripts looks a bit off

**Comment by callahantiff** [comment]
- [ ] weird content in output file, need to verify output form ontologies against new edges we add to isolate bug.
- [ ] Also want to think critically about how to add dbxrefs. May not be for `v2.0.0`, but I think adding this information will increase the usability of the result KG and make it easier for people to extend the KG with new data sources

**Comment by callahantiff** [comment]
- [ ] Export a dictionary for each node in the KG that contains two inner keys (i.e. `edge type` and `node type`) that can be used as a high-level way to organize the output data. This should be VERY simple to create for all builds.

A brief example of what this would like for node identifier `rs201492213` is shown below:

`node_type` = 'variant'
`edge_type` = ['variant-phenotype', 'variant-gene']

**Comment by callahantiff** [comment]
### TASK  
**Task Type:** [`CODEBASE`](https://github.com/callahantiff/PheKnowLator/projects/8#card-51636107)

Improve the output metadata for nodes and edges in the knowledge graph  


### TODO  
The following items have been condensed from the issues above.  
- [ ] Add a new column that includes the identifier and the integer (example shown [here](https://github.com/callahantiff/PheKnowLator/issues/58#issue-712343723))   
- [ ] Add relation information to metadata file. Will require a simple helper method to parse the graph and obtain relation labels  
- [ ] Verify output form ontologies against new edges we add to isolate bug  
- [ ] Also want to think critically about how to add dbxrefs. May not be for `v2.0.0`, but I think adding this information will increase the usability of the result KG and make it easier for people to extend the KG with new data sources  
- [ ] Export a dictionary for each node in the KG that contains two inner keys (i.e. `edge type` and `node type`) that can be used as a high-level way to organize the output data. This should be VERY simple to create for all builds  
- [ ] Should be able to work with metadata abstracted from the merged ontologies

**Comment by callahantiff** [comment]
Done as part of #84
