### ISSUE TITLE
Preparing for ISMB Bio-Ontologies Task 

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#67]
### Task  
Complete the needed tasks in order to get PheKnowLator prepared for the 2021 ISMB Bio-Ontologies Challenge. The specific tasks are organized and described below.

#### SPARQL Endpoint   
Not sure this is <u>actually</u> needed to support the challenge, but if it is, we need to answer the following question:  
- [ ] What do we use?  
- [ ] Where do we host it?  
- [ ] Do we want to think about using something other than SPARQL (i.e. `Neo4J`) that can support other 

#### Frequent Refresh of KG Builds  
- [x] Confirm with organizing committee which `pkt` build type to use - `OWL-NETS` versions of the builds are not true property graphs and may not be compatible with the evaluation framework. Probably want an instance and subclass build and their    
- [ ] Discuss potential changes that may be needed in order to create monthly KG updates to support challenge   
  - What needs to be done in the build framework for ontology preprocessing and other preprocessing steps in order to automate monthly builds   
    - Figure out about API set-up and requiring/providing keys for folks to download resources
    - Probably best to support a system that refreshes existing edge lists and not yet worry about sustaining/adding new edges sources yet  
    - Set-up CI system that builds it once a month and deposits files (see if this works with GitHub Actions)

**Comment by callahantiff** [comment]
@bill-baumgartner - confirmed the following details with Rob H this morning:
- OK, SPARQL Endpoint primarily used for evaluation, OK to provide KG data in other formats  
- Onboard with also providing a baseline embedding method

**Comment by callahantiff** [comment]
@bill-baumgartner - I am going to close this and open some new issues that will cover this and the work we discussed last night.
