### ISSUE TITLE
Setting Up and End-to-End CI/CD Framework

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#68]
### Task  
Determine which tools we will use in order to set-up an end-to-end CI/CD framework.   

**Task Type:** `Infrastructure`    

**Specs:** The requirements for this system include:  
- Leveraging GitHub Actions to:  
  - Test the codebase  
  - Downloaded needed resources and build the Docker Container  
  - Deploy and run the Docker container via Google Cloud Run (one for each KG build type).   
  - Returning all results  
  - Pushing certain files to Neo4J instance and SPARQL Endpoint

**Potential Configurations:**  
- CI/CD with Serverless Containers on GCP - Described [here](https://cloud.google.com/community/tutorials/cicd-cloud-run-github-actions)

**Related GitHub Issues:**  #47, #49

**Comment by callahantiff** [comment]
#### TODO  
- [ ] Script out data download and write to GCS (TASK 1)  
  - If any failure in download, default to last build's version of downloaded data and log issue   
- [ ] Script out preprocessing of LOD and Ontology data (TASK 2)    
  - Log any issues  
  - Output updated `resource_info.txt`, `edge_source_list.txt`, and `ontology_source_list.txt`  to DOcker container  
- [ ] Update Docker build trigger to pull from TASKS 1-2 (TASK 3)

**Comment by callahantiff** [comment]
Nearly done. The jobs are too long to use GitHub-hosted runners for GitHub Actions. Need to explore other options for self-hosted runner. Considering using [Terraform](https://github.com/terraform-google-modules/terraform-google-github-actions-runners).
