### ISSUE TITLE
Configure Google Cloud Storage

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#70]
### TASK  
**Task Type:** [`PKT DATA DELIVERY`](https://github.com/callahantiff/PheKnowLator/projects/8#card-51636129)

Use [Google Cloud Storage](https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwi7po-yyOLtAhXPwMAKHaHXAW8YABABGgJpbQ&ohost=www.google.com&cid=CAESQOD2LbD6PYbiY_dRGpdEviRONsIl_TIk8CnocpjUZhoV1IT8yDJhc0YhP8slczqDPY0MqQYQgqCUwLzv0fijB80&sig=AOD64_0SRUWhzfKj80R0vIgeDeSWnaXKDw&q&adurl&ved=2ahUKEwjAtISyyOLtAhWWWc0KHc6UCqkQ0Qx6BAgiEAE) in build to store each build's downloaded data and output knowledge graphs  
- Data used for each build  
- Built KGs  
- Built Embeddings  

#### TODO  
- [x] Create GCS Bucket for builds in GCP PheKnowLator bucket  (details [here](https://github.com/callahantiff/PheKnowLator/issues/70#issuecomment-750473635))  
- [x] Apply [Object Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle) to GCS bucket    
- [x] <s>Create script similar to [`google_cloud_storage_downloader.py`](https://github.com/callahantiff/OMOP2OBO/blob/master/google_cloud_storage_downloader.py) that can provides API access to Google Cloud Storage </s> 

**Resources:**  
- [Python API Tutorials](https://realpython.com/tutorials/api/)

**Comment by callahantiff** [comment]
This is what I am proposing for organizing the GCS bucket:  

```
GCS bucket root/  
    |---- pheknowlator/
    |     |---- knowledge_graph_builds/
    |     |    |---- release_v.1.0/ ...
    |     |    |---- release_v.2.0/
    |     |    |     |---- *build_<<date>>/
    |     |    |     |     |---- data/
    |     |    |     |     |     |---- original_data/
    |     |    |     |     |     |---- processed_data/   
    |     |    |     |     |---- knowledge_graphs/  
    |     |    |     |     |     |---- subclass_builds/
    |     |    |     |     |     |     |---- relations_only/
    |     |    |     |     |     |     |     |---- owl/
    |     |    |     |     |     |     |     |---- owlnets/     
    |     |    |     |     |     |     |---- inverse_relations/
    |     |    |     |     |     |     |     |---- owl/
    |     |    |     |     |     |     |     |---- owlnets/     
    |     |    |     |     |     |---- instance_builds/
    |     |    |     |     |     |     |---- relations_only/
    |     |    |     |     |     |     |     |---- owl/
    |     |    |     |     |     |     |     |---- owlnets/     
    |     |    |     |     |     |     |---- inverse_relations/
    |     |    |     |     |     |     |     |---- owl/
    |     |    |     |     |     |     |     |---- owlnets/    
    |     |    |     |---- *build_<<date>>/
```

For `release_v.1.0` data, I will update it once this work is complete and add files from past builds so that I am no longer responsible for maintaining them via my DropBox.

*meant to symbolize each monthly build

<br>

**GCS Permissions Setting:** I was thinking of setting the bucket `pheknowlator` directory and all subsequent directories as [nearline](https://cloud.google.com/storage/docs/storage-classes?_ga=2.259601736.-357560691.1606765671) to start and once we know what the usage pattern is we can adjust it.

<br> 

@bill-baumgartner - What do you think about this plan?

**Comment by bill-baumgartner** [comment]
I like the directory structure.  Do you expect to host other data aside from KG builds here? If not, then the `knowledge_graph_builds/` directory is probably not required.

It looks as though we can specify the storage class on a per-object level, and we can use [Object Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle) rules to change the storage class over time. So, a newly built KG could use the `Standard Storage` class initially, and then be downgraded to `Nearline Storage` after a period of time, e.g. 30 or 60 days.

**Comment by callahantiff** [comment]
> I like the directory structure. Do you expect to host other data aside from KG builds here? If not, then the `knowledge_graph_builds/` directory is probably not required.

I was thinking about that too. I'm guessing not, if we wanted to store a primary docker container or something like that, it wold likely be at the release-level. I will modify the figure to remove the `knowledge_graph_builds/` directory.

<br>

> It looks as though we can specify the storage class on a per-object level, and we can use [Object Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle) rules to change the storage class over time. So, a newly built KG could use the `Standard Storage` class initially, and then be downgraded to `Nearline Storage` after a period of time, e.g. 30 or 60 days.

Awesome, this is perfect. 

_____

✔️   I will go ahead and get this set-up now. It will allow me to start modifying/creating code we will need to support the three-task build plan we discussed yesterday.
