### ISSUE TITLE
Add Baseline KG Embeddings To CI/CD

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#71]
### TASK  
**Task Type:** [`CODEBASE`](https://github.com/callahantiff/PheKnowLator/projects/8#card-51636107)
 
Create code that generates a single set of baseline embeddings for each KG build output by PheKnowLator. This code should be run as part of the CD/CI

#### TODO  
- [ ] Choose an embedding method  
  - [CSR + Node2Vec](https://gist.github.com/callahantiff/9c42f14699a45d2e43cac154947fcd84)   
  - [Embiggen](https://github.com/monarch-initiative/embiggen)  
- [ ] Select reasonable hyperparameter settings for each `OWL` and `OWL-NETS` build  
- [ ] Incorporate build into CI/CD workflow (#68)

**Comment by callahantiff** [comment]
Holding off on adding embeddings until evaluation complete. This will allow us to select the most appropriate kinds of embeddings to incorporate into the monthly builds. Closing for now. Will open new issue after paper is submitted.
