### ISSUE TITLE
Convert Data Preprocessing Jupyter Notebook to Script

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#72]
### TASK  
**Task Type:** [`CODEBASE`](https://github.com/callahantiff/PheKnowLator/projects/8#card-51636107)
 
Convert the code in the [`Data_Preparation.ipynb`](https://github.com/callahantiff/PheKnowLator/blob/master/Data_Preparation.ipynb) into a script that can be run as part of the KG CI/CD build.  

#### TODO  
- [ ] Convert notebook to script  
- [ ] Write tests against script  
- [ ] Integrate script into CI/CD workflow (#68)
