### ISSUE TITLE
Convert Ontology Cleaning Jupyter Notebook into Script

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#73]
### TASK  
**Task Type:** [`CODEBASE`](https://github.com/callahantiff/PheKnowLator/projects/8#card-51636107)

Convert the code in the [`Ontology_Cleaning.ipynb`](https://github.com/callahantiff/PheKnowLator/blob/master/Ontology_Cleaning.ipynb) into a script that can be run as part of the KG CI/CD build.  

#### TODO  
- [ ] Convert notebook to script  
- [ ] Write tests against script  
- [ ] Integrate script into CI/CD workflow (#68)
