### ISSUE TITLE
Handling MESH-CHEBI Mappings

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#77]
### TASK  
**Task Type:** [`CODEBASE`](https://github.com/callahantiff/PheKnowLator/projects/8#card-51636107)

Decide how to handle `MESH` to `CHEBI` mappings. Currently there is a GitHub Gist ([`ncbo_rest_api.py`](https://gist.github.com/callahantiff/a28fb3160782f42f104e9ec41553af0d)) that pings the [BioPortal API](http://data.bioontology.org/documentation) into a script that can be run as part of the KG CI/CD build.

*Problems:* The `ncbo_rest_api.py` script runs fine, but it's brittle given its reliance on the BioPortal API, which is notoriously unstable. A potential solution (for now or in the future) could be implement the [LOOM](https://www.bioontology.org/wiki/BioPortal_Mappings) algorithm which is what creates the mappings underlying the API.

#### TODO  
- [x] Decide whether or not to use current script or implement LOOM  
- [x] Convert Gist to script  
- [x] <s>Write tests against script</s>  
- [x] Integrate script into CI/CD workflow (#68)

**Comment by callahantiff** [comment]
This work impacts issue #72 because of its reference in the associated Jupyter Notebook.

**Comment by callahantiff** [comment]
@bill-baumgartner - this is complete (will be integrated with PR #81). I followed the details for the `LOOM` algorithm described on the BioPortal Wiki. It's very simple, just a few methods. Since there is nothing fancy, essentially accomplished through some preprocessing of the input MesH and ChEBI data and performing an inner join to find overlapping concepts.

**In a Nutshell:** We download the [`mesh2021.nt`](ftp://nlmpubs.nlm.nih.gov/online/mesh/rdf/2021/mesh2021.nt) data file directly from MeSH and the [`Flat_file_tab_delimited/names.tsv.gz`](ftp://ftp.ebi.ac.uk/pub/databases/chebi/Flat_file_tab_delimited/names.tsv.gz) file directly from ChEBI. Using these files, we have recapitulated the [`LOOM`](https://www.bioontology.org/wiki/BioPortal_Mappings) algorithm implemented by BioPortal when creating mappings between these resources. The procedure is relatively straightforward and utilizes the following information from each resource:
- For all MeSH `SCR Chemicals`, obtain the following information:  
  - <u>Identifiers</u>: MeSH identifiers     
  - <u>Labels</u>: string labels using the `RDFS:label` object property  
  - <u>Synonyms</u>: track down all synonyms using the `vocab:concept` and `vocab:preferredConcept` object properties   
- For all ChEBI classes, obtain the following information:  
  - <u>Labels</u>: string labels using the `RDFS:label` object property  
  - <u>Synonyms</u>: track down all synonyms using all `synonym` object properties  

You can see details with a description in the notebook [here](https://github.com/callahantiff/PheKnowLator/blob/scripting_prebuild_notebooks/Data_Preparation.ipynb) under `ChEBI Identifiers` as well as in the scripted version of this notebook (lines: 496-628, [here](https://github.com/callahantiff/PheKnowLator/blob/scripting_prebuild_notebooks/builds/data_preprocessing.py))
